# Generated by Django 5.1.6 on 2025-02-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='audio_file',
            field=models.FileField(null=True, upload_to='audio/'),
        ),
    ]
